test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= Rails.application.secrets.dig(:storage, :private, :access_key_id) %>
  secret_access_key: <%= Rails.application.secrets.dig(:storage, :private, :secret_access_key) %>
  region: <%= Rails.application.secrets.dig(:storage, :private, :region) %>
  bucket: <%= Rails.application.secrets.dig(:storage, :private, :bucket) %>

amazon_public:
  service: S3
  public: true
  access_key_id: <%= Rails.application.secrets.dig(:storage, :public, :access_key_id) %>
  secret_access_key: <%= Rails.application.secrets.dig(:storage, :public, :secret_access_key) %>
  region: <%= Rails.application.secrets.dig(:storage, :public, :region) %>
  bucket: <%= Rails.application.secrets.dig(:storage, :public, :bucket) %>
