test: &test
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

test_public:
  <<: *test
  public: true

local: &local
  service: Disk
  root: <%= Rails.root.join("storage") %>

local_public:
  <<: *local
  public: true

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= Rails.application.secrets.dig(:storage, :private, :access_key_id) %>
  secret_access_key: <%= Rails.application.secrets.dig(:storage, :private, :secret_access_key) %>
  region: <%= Rails.application.secrets.dig(:storage, :private, :region) %>
  bucket: <%= Rails.application.secrets.dig(:storage, :private, :bucket) %>

amazon_public:
  service: S3
  public: true
  access_key_id: <%= Rails.application.secrets.dig(:storage, :public, :access_key_id) %>
  secret_access_key: <%= Rails.application.secrets.dig(:storage, :public, :secret_access_key) %>
  region: <%= Rails.application.secrets.dig(:storage, :public, :region) %>
  bucket: <%= Rails.application.secrets.dig(:storage, :public, :bucket) %>

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
